name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'hotfix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'deps'
  - title: '📝 Documentation & Tests'
    labels:
      - 'docs'
      - 'test'
  - title: '🎨 UI & UX'
    labels:
      - 'ui'
      - 'accessibility'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No changes in this release.'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'hotfix'
      - 'chore'
      - 'refactor'
      - 'deps'
      - 'docs'
      - 'test'
      - 'ui'
      - 'accessibility'

template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
