name: Build and Upload APK to Draft Release

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Get latest draft release tag
        id: get_draft_tag
        run: |
          latest_draft=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases" | \
            jq -r '.[] | select(.draft==true) | .tag_name' | head -n 1)

          echo "Latest draft release tag: $latest_draft"
          echo "TAG_NAME=$latest_draft" >> $GITHUB_ENV

      - name: Upload APK to draft release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: app/build/outputs/apk/release/app-release.apk
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
